# Generated by Django 3.1 on 2023-05-22 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consume',
            name='user',
        ),
    ]
